### ISSUE TITLE
jonlil/ckfinder down - project removed from github!

### ISSUE THREAD

**Issue by 42antoine** [jonlil/JonlilCKFinderBundle#32]
jonlil/ckfinder down - project removed from github!

**Comment by 42antoine** [comment]
https://github.com/jonlil/ckfinder

**Comment by jonlil** [comment]
yes, I had to take it down because it was against ckfinder license. You could always download the ckfinder source by yourself

**Comment by 42antoine** [comment]
I'll do as you advice me and use the following package : ckfinder/ckfinder-symfony2-bundle.

Thanks for the very fast reply.

**Comment by jonlil** [comment]
no problem and sorry for the inconvenience
