### ISSUE TITLE
Dependency "jonlil/ckfinder" repository no longer exists.

### ISSUE THREAD

**Issue by dave-newson** [jonlil/JonlilCKFinderBundle#35]
This bundle has a dependency on your jonlil/ckfinder repository. That repository is no longer available:
`https://github.com/jonlil/ckfinder`

Accidentally deleted? Github cockup?

**Comment by jonlil** [comment]
ckfinder license trouble :(
They hey released their own bundle under https://github.com/ckfinder/ckfinder-symfony2-bundle

**Comment by dave-newson** [comment]
@jonlil I notice the last 4 closed bugs are basically all about this. Could you do some of the following:
1. Hop onto packagist.org and flag both repositories as abandoned, suggesting the ckfinder replacement.
2. Add something to the readme of this package which indicates it's now abandoned and suggest the ckfinder replacement.
